### ISSUE TITLE
Validating HTML5 Documents does not work

### ISSUE THREAD

**Issue by surjithctly** [dubharmonic/Sublime-W3CValidators#8]
Validating HTML5 Documents does not work. 
It throws this error in console : 

    Traceback (most recent call last):
      File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
        return self.run(edit)
      File "W3CValidators in C:\Users\USER\AppData\Roaming\Sublime Text 3\Installed      Packages\W3CValidators.sublime-package", line 54, in run
      File "W3CValidators in C:\Users\USER\AppData\Roaming\Sublime Text 3\Installed     Packages\W3CValidators.sublime-package", line 44, in validate
    KeyError: 'lastLine'

Windows 8.1 => Sublime 3 latest.

**Comment by LOQUILLO** [comment]
Validating HTML5 Documents does not work.
ST 3 Build 3083
Windows 7 x64
Console showme this error:

Traceback (most recent call last):
  File "./json/decoder.py", line 368, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "W3CValidators in C:\Users\TEST\AppData\Roaming\Sublime Text 3\Installed Packages\W3CValidators.sublime-package", line 54, in run
  File "W3CValidators in C:\Users\TEST\AppData\Roaming\Sublime Text 3\Installed Packages\W3CValidators.sublime-package", line 33, in validate
  File "./json/__init__.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 370, in raw_decode
ValueError: No JSON object could be decoded

**Comment by trinaldi** [comment]
It looks like they changed the URL for HTML5 tests.

Reading the [W3C Documentation](https://validator.w3.org/docs/api.html), they provide some tests for the developers. Here's the link: https://validator.w3.org/dev/tests/

If you check the HTML5 test the end URL is no longer the same as the other ones:
HTML5 -> https://validator.w3.org/nu
Other formats -> https://validator.w3.org/check

This plugin uses the second one, thus the HTML5 document won't be available for checking. Another thing to keep in mind is that the HTML5 validation is experimental (according to the W3C site).

**Comment by surjithctly** [comment]
Any chance to fix that?

**Comment by trinaldi** [comment]
I don't see a solution in the near future. But, I'm not a ST Package developer, I'm just assuming regarding the documentation.

Checking the new html checker [docs](https://validator.w3.org/nu/about.html), it looks like it depends a lot on Java. Even the Python solution executes an instance of their Java program.

Apparently, they are under a redesign. Let's hope they use a similar method for HTML5.

Meanwhile, you can check your code manually using https://validator.w3.org/nu/#textarea

**Comment by dubharmonic** [comment]
Thanks for finding this @surjithctly ! I just returned from a vacation, I should be able to fix this in the next few days.

**Comment by dubharmonic** [comment]
0.4.0 released. Please let me know if this doesn't fix the issue.

**Comment by LOQUILLO** [comment]
Hi @dubharmonic it's fixed

**Comment by surjithctly** [comment]
@dubharmonic Woohoo.. Thanks for the fix.. Works like a Charm.. Appreciate it :+1:

**Comment by trinaldi** [comment]
Nice, @dubharmonic . Thanks!

**Comment by surjithctly** [comment]
Hello Again @dubharmonic ,

Seems HTML5 Validation not working again and throwing this error : 

```
Traceback (most recent call last):
  File "./json/decoder.py", line 368, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "W3CValidators in C:\Users\USER\AppData\Roaming\Sublime Text 3\Installed Packages\W3CValidators.sublime-package", line 64, in run
  File "C:\Users\USER\AppData\Roaming\SUBLIM~1\Packages\requests\all\requests\models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "./json/__init__.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 370, in raw_decode
ValueError: No JSON object could be decoded
```

Anyone having the same issue again?

**Comment by LOQUILLO** [comment]
Hi @surjithctly here is working very fine, first remove W3CValidators package, reinstall and test again.

**Comment by LOQUILLO** [comment]
W3CValidators is working with somes html5 files but not with others ones, console show this:
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "W3CValidators in C:\Users\TEST\AppData\Roaming\Sublime Text 3\Installed Packages\W3CValidators.sublime-package", line 75, in run
KeyError: 'lastLine'

**Comment by LOQUILLO** [comment]
A trick, If i click into file, then after go to context menu W3C Validators - HTML5 and file is checked ok. Maybe there are a delay with server check.

**Comment by surjithctly** [comment]
Hi @dubharmonic  @LOQUILLO 

It started working again. I think the issue is caused because at that time, The validator.nu was also down (Bad Gateway)

Can't we set a backup API if the first server is down? Also it will be good if there's an error message shown as "Server Down".

~Surjith

**Comment by LOQUILLO** [comment]
hi @surjithctly "Server Down" message will be a goal!!!

**Comment by JackNel** [comment]
Hi all,

Has this issue resurfaced for anyone else? I've been using the validator plug-in for a few months and started getting this error at the beginning of this week (10/31/2016)

**Comment by surjithctly** [comment]
HTML5 Validations stopped working again..   Same error as I mentioned above: #issuecomment-168184900

**Comment by surjithctly** [comment]
@dubharmonic Any help this time?
